import hashlib
import reprlib
from pathlib import Path
from datetime import datetime
from typing import Any
from urllib.parse import urlparse

from curl_cffi.requests import AsyncSession
from curl_cffi.requests.exceptions import HTTPError
from pydantic import BaseModel

from ..utils import logger


class Image(BaseModel):
    """A single image object returned from Gemini.

    Attributes:
        url (str): URL of the image.
        title (str, optional): Title of the image. Defaults to "[Image]".
        alt (str, optional): Optional description of the image.
        proxy (str, optional): Proxy used when saving image.
        client (Any, optional): Reference to the client object.
    """

    url: str
    title: str = "[Image]"
    alt: str = ""
    proxy: str | None = None
    client: Any = None

    def __str__(self):
        return f"Image(title='{self.title}', alt='{self.alt}', url='{reprlib.repr(self.url)}')"

    async def save(
        self,
        path: str = "temp",
        filename: str | None = None,
        verbose: bool = False,
        skip_invalid_filename: bool = False,
        client: AsyncSession | None = None,
    ) -> str | None:
        """Saves the image to disk.

        Args:
            path (str, optional): Path to save the image. Defaults to "./temp".
            filename (str | None, optional): File name to save the image. Defaults to
                the original file name from the URL.
            verbose (bool, optional): If True, will print the path of the saved file
                or warning for invalid file name. Defaults to False.
            skip_invalid_filename (bool, optional): If True, will only save the image
                if the file name and extension are valid. Defaults to False.
            client (AsyncSession | None, optional): Client used for requests.

        Returns:
            str | None: Absolute path of the saved image if successful, None if
                filename is invalid and `skip_invalid_filename` is True.

        Raises:
            curl_cffi.requests.exceptions.HTTPError: If the network request failed.
        """

        if not filename:
            parsed_url = urlparse(self.url)
            filename = Path(parsed_url.path).name

        if not Path(filename).suffix:
            if skip_invalid_filename:
                if verbose:
                    logger.warning(f"Invalid filename: {filename}")
                return None
            else:
                timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
                url_hash = hashlib.sha256(self.url.encode()).hexdigest()[:10]
                filename = f"{timestamp}_{url_hash}.png"

        close_client = False
        req_client = client or self.client
        if not req_client:
            req_client = AsyncSession(
                impersonate="chrome",
                allow_redirects=True,
                proxy=self.proxy,
            )
            close_client = True

        try:
            response = await req_client.get(self.url)
            if verbose:
                logger.debug(f"HTTP Request: GET {self.url} [{response.status_code}]")
            if response.status_code == 200:
                content_type = response.headers.get("content-type")
                if content_type and "image" not in content_type:
                    logger.warning(
                        f"Content type of {filename} is not image, but {content_type}."
                    )

                path_obj = Path(path)
                path_obj.mkdir(parents=True, exist_ok=True)

                dest = path_obj / filename
                dest.write_bytes(response.content)

                if verbose:
                    logger.info(f"Image saved as {dest.resolve()}")

                return str(dest.resolve())
            else:
                raise HTTPError(
                    f"Error downloading image: {response.status_code} {response.reason}"
                )
        finally:
            if close_client:
                await req_client.close()


class WebImage(Image):
    """Image retrieved from web.

    Returned when asking Gemini to "SEND an image of [something]".
    """

    pass


class GeneratedImage(Image):
    """Image generated by Google's AI image generator.

    Returned when asking Gemini to "GENERATE an image of [something]".

    Attributes:
        client_ref (Any, optional): Reference to the GeminiClient instance.
        cid (str, optional): Chat ID.
        rid (str, optional): Response ID.
        rcid (str, optional): Response candidate ID.
        image_id (str, optional): Image ID generated.
    """

    client_ref: Any = None
    cid: str = ""
    rid: str = ""
    rcid: str = ""
    image_id: str = ""

    # @override
    async def save(
        self,
        path: str = "temp",
        filename: str | None = None,
        verbose: bool = False,
        skip_invalid_filename: bool = False,
        full_size: bool = True,
        client: AsyncSession | None = None,
    ) -> str | None:
        """Saves the generated image to disk.

        Args:
            path (str, optional): Path to save the image. Defaults to "temp".
            filename (str | None, optional): Filename to save the image. Generated images
                are always in .png format, but the file extension is not included in the URL.
                Defaults to timestamp + the end of the URL hash.
            verbose (bool, optional): Prints the path of the saved file or warning if True. Defaults to False.
            skip_invalid_filename (bool, optional): Saves the image only if the file name is valid. Defaults to False.
            full_size (bool, optional): Modifies preview URLs to fetch full-size images if True. Defaults to True.
            client (AsyncSession | None, optional): An existing AsyncSession client. Defaults to None.

        Returns:
            str | None: Absolute path of the saved image if successfully saved, None otherwise.
        """
        if full_size:
            if all([self.client_ref, self.cid, self.rid, self.rcid, self.image_id]):
                try:
                    original_url = await self.client_ref._get_image_full_size(
                        cid=self.cid,
                        rid=self.rid,
                        rcid=self.rcid,
                        image_id=self.image_id,
                    )
                    if original_url:
                        req_url = f"{original_url}=d-I?alr=yes"

                        req_client = client or self.client
                        close_client = False

                        if not req_client:
                            req_client = AsyncSession(
                                impersonate="chrome",
                                allow_redirects=True,
                                cookies=(
                                    self.client_ref.cookies if self.client_ref else None
                                ),
                                proxy=self.proxy,
                            )
                            close_client = True

                        try:
                            response = await req_client.get(req_url)
                            response.raise_for_status()
                            url_text = response.text

                            response = await req_client.get(url_text)
                            response.raise_for_status()
                            self.url = response.text

                            return await super().save(
                                path=path,
                                filename=filename,
                                verbose=verbose,
                                skip_invalid_filename=skip_invalid_filename,
                                client=req_client,
                            )
                        finally:
                            if close_client and req_client:
                                await req_client.close()

                except Exception as e:
                    logger.debug(
                        f"Failed to fetch full size image URL via RPC: {e}, falling back to default URL suffix."
                    )

            if "=s1024-rj" in self.url:
                self.url = self.url.replace("=s1024-rj", "=s2048-rj")
            elif "=s2048-rj" not in self.url:
                self.url += "=s2048-rj"
        else:
            if "=s2048-rj" in self.url:
                self.url = self.url.replace("=s2048-rj", "=s1024-rj")
            elif "=s1024-rj" not in self.url:
                self.url += "=s1024-rj"

        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            url_hash = hashlib.sha256(self.url.encode()).hexdigest()[:10]
            filename = f"{timestamp}_{url_hash}.png"

        return await super().save(
            path=path,
            filename=filename,
            verbose=verbose,
            skip_invalid_filename=skip_invalid_filename,
            client=client,
        )
