import asyncio
import hashlib
import mimetypes
import reprlib
from datetime import datetime
from pathlib import Path
from typing import Any

from curl_cffi.requests import AsyncSession
from curl_cffi.requests.exceptions import HTTPError
from pydantic import BaseModel

from ..utils import logger


class Video(BaseModel):
    """A single video object returned from Gemini.

    Attributes:
        url (str): URL of the video.
        title (str, optional): Title of the video. Defaults to "[Video]".
        proxy (str, optional): Proxy used when saving video.
        client (Any, optional): Reference to the client object.
    """

    url: str
    title: str = "[Video]"
    proxy: str | None = None
    client: Any = None

    def __str__(self):
        return f"Video(title='{self.title}', url='{reprlib.repr(self.url)}')"

    async def save(
        self,
        path: str = "temp",
        filename: str | None = None,
        verbose: bool = False,
        skip_invalid_filename: bool = False,
        client: AsyncSession | None = None,
    ) -> tuple[str | None, str | None]:
        """Saves the video to disk.

        Args:
            path (str, optional): Path to save the video. Defaults to "./temp".
            filename (str | None, optional): File name to save the video. Defaults to
                a unique generated name.
            verbose (bool, optional): If True, will print the path of the saved file.
            skip_invalid_filename (bool, optional): If True, will only save the video
                if the file name has a valid extension. Defaults to False.
            client (AsyncSession | None, optional): Client used for requests.

        Returns:
            tuple[str | None, str | None]: (Absolute path of the saved video, str | None path of thumbnail)
        """

        if not filename or not Path(filename).suffix:
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            url_hash = hashlib.sha256(self.url.encode()).hexdigest()[:10]
            base_name = Path(filename).stem if filename else "video"
            filename = f"{timestamp}_{url_hash}_{base_name}"

        close_client = False
        req_client = client or self.client
        if not req_client:
            client_ref = getattr(self, "client_ref", None)
            cookies = getattr(client_ref, "cookies", None) if client_ref else None
            req_client = AsyncSession(
                impersonate="chrome",
                allow_redirects=True,
                cookies=cookies,
                proxy=self.proxy,
            )
            close_client = True

        try:
            path_obj = Path(path)
            path_obj.mkdir(parents=True, exist_ok=True)
            return await self._perform_save(req_client, path_obj, filename, verbose)
        finally:
            if close_client:
                await req_client.close()

    @staticmethod
    async def _download_file(
        req_client: AsyncSession,
        url: str,
        path_obj: Path,
        filename: str,
        default_ext: str = ".mp4",
        verbose: bool = False,
    ) -> str | None:
        """Internal helper to download a file and determine its extension."""
        response = await req_client.get(url)
        if verbose:
            logger.debug(f"HTTP Request: GET {url} [{response.status_code}]")

        if response.status_code == 200:
            path_obj_file = Path(filename)
            if not path_obj_file.suffix:
                content_type = (
                    response.headers.get("content-type", "")
                    .split(";")[0]
                    .strip()
                    .lower()
                )
                ext = mimetypes.guess_extension(content_type) or default_ext
                filename = f"{filename}{ext}"

            dest = path_obj / filename
            dest.write_bytes(response.content)

            if verbose:
                logger.info(f"File saved as {dest.resolve()}")

            return str(dest.resolve())
        elif response.status_code == 206:
            return "206"
        else:
            raise HTTPError(
                f"Error downloading file: {response.status_code} {response.reason}"
            )

    async def _perform_save(
        self, req_client: AsyncSession, path_obj: Path, filename: str, verbose: bool
    ) -> tuple[str | None, str | None]:
        """Base implementation: simple download."""
        path = await self._download_file(
            req_client, self.url, path_obj, filename, ".mp4", verbose
        )
        return path, None


class GeneratedVideo(Video):
    """Video generated by Google's AI Veo.

    Attributes:
        client_ref (Any, optional): Reference to the GeminiClient instance.
        thumbnail (str, optional): URL of the video thumbnail.
        cid (str, optional): Chat ID.
        rid (str, optional): Response ID.
        rcid (str, optional): Response candidate ID.
    """

    client_ref: Any = None
    thumbnail: str = ""
    cid: str = ""
    rid: str = ""
    rcid: str = ""

    # @override
    async def _perform_save(
        self, req_client: AsyncSession, path_obj: Path, filename: str, verbose: bool
    ) -> tuple[str | None, str | None]:
        """Internal method for GeneratedVideo, handling thumbnails and polling."""
        saved_thumb_path = None
        if self.thumbnail:
            thumb_base = Path(filename).stem
            try:
                saved_thumb_path = await self._download_file(
                    req_client, self.thumbnail, path_obj, thumb_base, ".jpg", verbose
                )
            except Exception as e:
                if verbose:
                    logger.warning(f"Failed to save thumbnail: {e}")

        while True:
            path_or_marker = await self._download_file(
                req_client, self.url, path_obj, filename, ".mp4", verbose
            )

            if path_or_marker == "206":
                if verbose:
                    logger.info("Video still generating (206), retrying in 10s...")
                await asyncio.sleep(10)
            else:
                return path_or_marker, saved_thumb_path
